// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZKNWYACiPDL7JquAZabho8g7RNNKKhwU',
    appId: '1:685308416724:web:88d75f0bba9c3fcf5b2141',
    messagingSenderId: '685308416724',
    projectId: 'drone-ecommerce-3a480',
    authDomain: 'drone-ecommerce-3a480.firebaseapp.com',
    storageBucket: 'drone-ecommerce-3a480.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoROkijibknQ89pehLrk9WN-umOPaRkT0',
    appId: '1:685308416724:android:0fe86adfc8cbee325b2141',
    messagingSenderId: '685308416724',
    projectId: 'drone-ecommerce-3a480',
    storageBucket: 'drone-ecommerce-3a480.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY7nPy1_YFXUE7T6ZXlRbuvuqoA2IfZbI',
    appId: '1:685308416724:ios:cdd1bca72493f6485b2141',
    messagingSenderId: '685308416724',
    projectId: 'drone-ecommerce-3a480',
    storageBucket: 'drone-ecommerce-3a480.firebasestorage.app',
    iosBundleId: 'com.example.ecommercephp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY7nPy1_YFXUE7T6ZXlRbuvuqoA2IfZbI',
    appId: '1:685308416724:ios:cdd1bca72493f6485b2141',
    messagingSenderId: '685308416724',
    projectId: 'drone-ecommerce-3a480',
    storageBucket: 'drone-ecommerce-3a480.firebasestorage.app',
    iosBundleId: 'com.example.ecommercephp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZKNWYACiPDL7JquAZabho8g7RNNKKhwU',
    appId: '1:685308416724:web:ff2385f636e06b475b2141',
    messagingSenderId: '685308416724',
    projectId: 'drone-ecommerce-3a480',
    authDomain: 'drone-ecommerce-3a480.firebaseapp.com',
    storageBucket: 'drone-ecommerce-3a480.firebasestorage.app',
  );
}